// A small built-in directory of well-known US tickers. Used to give CBOE
// fallback quotes a human name and to power offline search when Yahoo's
// search endpoint is unreachable. Not exhaustive — just the names beginners
// are most likely to look for.

export const KNOWN_SYMBOLS: Record<string, string> = {
  AAPL: "Apple Inc.",
  MSFT: "Microsoft Corporation",
  GOOGL: "Alphabet Inc. (Google)",
  GOOG: "Alphabet Inc. (Google)",
  AMZN: "Amazon.com, Inc.",
  NVDA: "NVIDIA Corporation",
  META: "Meta Platforms (Facebook)",
  TSLA: "Tesla, Inc.",
  "BRK.B": "Berkshire Hathaway Inc.",
  JPM: "JPMorgan Chase & Co.",
  V: "Visa Inc.",
  MA: "Mastercard Incorporated",
  UNH: "UnitedHealth Group",
  JNJ: "Johnson & Johnson",
  WMT: "Walmart Inc.",
  PG: "Procter & Gamble",
  HD: "The Home Depot",
  KO: "The Coca-Cola Company",
  PEP: "PepsiCo, Inc.",
  MCD: "McDonald's Corporation",
  DIS: "The Walt Disney Company",
  NFLX: "Netflix, Inc.",
  INTC: "Intel Corporation",
  AMD: "Advanced Micro Devices",
  CRM: "Salesforce, Inc.",
  ORCL: "Oracle Corporation",
  ADBE: "Adobe Inc.",
  CSCO: "Cisco Systems",
  IBM: "IBM Corporation",
  QCOM: "Qualcomm Incorporated",
  AVGO: "Broadcom Inc.",
  TXN: "Texas Instruments",
  BA: "The Boeing Company",
  CAT: "Caterpillar Inc.",
  GE: "General Electric",
  F: "Ford Motor Company",
  GM: "General Motors",
  XOM: "Exxon Mobil Corporation",
  CVX: "Chevron Corporation",
  PFE: "Pfizer Inc.",
  MRK: "Merck & Co.",
  ABBV: "AbbVie Inc.",
  LLY: "Eli Lilly and Company",
  BAC: "Bank of America",
  WFC: "Wells Fargo & Company",
  GS: "The Goldman Sachs Group",
  MS: "Morgan Stanley",
  C: "Citigroup Inc.",
  T: "AT&T Inc.",
  VZ: "Verizon Communications",
  NKE: "NIKE, Inc.",
  SBUX: "Starbucks Corporation",
  ABNB: "Airbnb, Inc.",
  UBER: "Uber Technologies",
  LYFT: "Lyft, Inc.",
  SHOP: "Shopify Inc.",
  PYPL: "PayPal Holdings",
  SQ: "Block, Inc. (Square)",
  COIN: "Coinbase Global",
  PLTR: "Palantir Technologies",
  SNOW: "Snowflake Inc.",
  SPOT: "Spotify Technology",
  RBLX: "Roblox Corporation",
  HOOD: "Robinhood Markets",
  GME: "GameStop Corp.",
  AMC: "AMC Entertainment",
  COST: "Costco Wholesale",
  TGT: "Target Corporation",
  LOW: "Lowe's Companies",
  DAL: "Delta Air Lines",
  UAL: "United Airlines",
  AAL: "American Airlines",
  MRNA: "Moderna, Inc.",
  // Popular ETFs
  SPY: "SPDR S&P 500 ETF",
  VOO: "Vanguard S&P 500 ETF",
  IVV: "iShares Core S&P 500 ETF",
  VTI: "Vanguard Total Stock Market ETF",
  QQQ: "Invesco QQQ (Nasdaq-100 ETF)",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  IWM: "iShares Russell 2000 ETF",
  VXUS: "Vanguard Total International Stock ETF",
  BND: "Vanguard Total Bond Market ETF",
  ARKK: "ARK Innovation ETF",
  GLD: "SPDR Gold Shares",
  SCHD: "Schwab US Dividend Equity ETF",
  VIG: "Vanguard Dividend Appreciation ETF",
  VGT: "Vanguard Information Technology ETF",
  XLK: "Technology Select Sector SPDR",
  XLE: "Energy Select Sector SPDR",
  XLF: "Financial Select Sector SPDR",
};
